version: "3.3"

services:
  vue-cli:
    container_name: vue
    command: "vue ui --headless --port 8000 --host 0.0.0.0"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - ./:/code
    working_dir: /code
    stdin_open: true
    tty: true
    ports:
    - "8080:8080"
    - "8000:8000"
    networks:
      - frontend
networks:
  frontend:
